import { useDocuments, useGeneration } from "../../hooks/useDocuments";
import type { DocType } from "../../hooks/useDocuments";
import { Markdown } from "../../lib/markdown";
import { EmptyState, ErrorBanner } from "../../components/Feedback";
import { ApiError } from "../../services/api";

const LABELS: Record<DocType, string> = {
  summary: "Summary",
  document: "Document",
};

interface GeneratedDocsPanelProps {
  boxId: number;
  active: DocType;
  onChangeTab(type: DocType): void;
}

/**
 * Cached AI outputs for a box, shown in Summary / Document tabs.
 * Both generation buttons live here so they can disable each other while
 * either request is running.
 */
export function GeneratedDocsPanel({ boxId, active, onChangeTab }: GeneratedDocsPanelProps) {
  const documentsQuery = useDocuments(boxId);
  const { summary: summaryMutation, document: documentMutation, isGenerating } =
    useGeneration(boxId);

  const documents = documentsQuery.data ?? [];
  const summaryDoc = documents.find((doc) => doc.type === "summary");
  const documentDoc = documents.find((doc) => doc.type === "document");

  const error =
    summaryMutation.error instanceof ApiError
      ? summaryMutation.error.message
      : documentMutation.error instanceof ApiError
        ? documentMutation.error.message
        : null;

  function generate() {
    if (isGenerating) return;
    if (active === "summary") {
      summaryMutation.mutate();
    } else {
      documentMutation.mutate();
    }
  }

  const generatingLabel = summaryMutation.isPending
    ? "Generating summary…"
    : documentMutation.isPending
      ? "Generating document…"
      : null;

  const activeDoc = active === "summary" ? summaryDoc : documentDoc;

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      {/* Generation controls + panel tabs */}
      <div className="flex flex-wrap items-center gap-2 border-b border-neutral-200 bg-white px-4 py-2.5 md:px-6">
        <div className="flex overflow-hidden rounded-md border border-neutral-200">
          {(Object.keys(LABELS) as DocType[]).map((type) => (
            <button
              key={type}
              type="button"
              onClick={() => onChangeTab(type)}
              className={`px-3 py-1.5 text-xs font-medium ${
                active === type
                  ? "bg-neutral-900 text-white"
                  : "bg-white text-neutral-600 hover:bg-neutral-50"
              }`}
            >
              {LABELS[type]}
            </button>
          ))}
        </div>

        <div className="ml-auto flex items-center gap-2">
          {generatingLabel && (
            <span className="text-xs text-neutral-500" role="status">
              {generatingLabel}
            </span>
          )}
          <button
            type="button"
            onClick={generate}
            disabled={isGenerating || documentsQuery.isPending}
            className="rounded-md bg-neutral-900 px-3 py-1.5 text-xs font-medium text-white transition-colors hover:bg-neutral-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {active === "summary"
              ? summaryDoc
                ? "Regenerate Summary"
                : "Generate Summary"
              : documentDoc
                ? "Regenerate Document"
                : "Generate Document"}
          </button>
        </div>
      </div>

      {error && (
        <div className="px-4 pt-3 md:px-6">
          <ErrorBanner message={error} />
        </div>
      )}

      {/* Rendered markdown */}
      <div className="min-h-0 flex-1 overflow-y-auto px-4 py-5 md:px-6">
        {generatingLabel && !activeDoc ? (
          <p className="text-sm text-neutral-400">{generatingLabel.replace("…", "...")}</p>
        ) : documentsQuery.isError ? (
          <ErrorBanner
            message={
              documentsQuery.error instanceof ApiError
                ? documentsQuery.error.message
                : "Could not load generated content."
            }
          />
        ) : activeDoc ? (
          <article className="mx-auto max-w-3xl rounded-lg border border-neutral-200 bg-white p-5 shadow-sm md:p-8">
            <Markdown content={activeDoc.content} />
            <footer className="mt-8 border-t border-neutral-100 pt-3 text-[11px] text-neutral-400">
              Generated by {activeDoc.model} · Updated{" "}
              {new Date(activeDoc.updatedAt).toLocaleString()}
            </footer>
          </article>
        ) : (
          <EmptyState
            title={`No ${active === "summary" ? "summary" : "document"} yet.`}
            hint={
              active === "summary"
                ? 'Click "Generate Summary" to turn this box\'s thoughts into a structured overview.'
                : 'Click "Generate Document" to produce a complete document from this box.'
            }
          />
        )}
      </div>
    </div>
  );
}
